# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CompositeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(669, 451)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Dialog.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_bg_select = QtWidgets.QPushButton(Dialog)
        self.pushButton_bg_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_bg_select.setObjectName("pushButton_bg_select")
        self.horizontalLayout.addWidget(self.pushButton_bg_select)
        self.pushButton_subject_select = QtWidgets.QPushButton(Dialog)
        self.pushButton_subject_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_subject_select.setObjectName("pushButton_subject_select")
        self.horizontalLayout.addWidget(self.pushButton_subject_select)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_bg = QtWidgets.QLabel(self.groupBox)
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.verticalLayout.addWidget(self.label_bg)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_subject = QtWidgets.QLabel(self.groupBox_2)
        self.label_subject.setText("")
        self.label_subject.setObjectName("label_subject")
        self.verticalLayout_2.addWidget(self.label_subject)
        self.verticalLayout_3.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_3.setStretch(1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_bg_select.setText(_translate("Dialog", "选择背景图"))
        self.pushButton_subject_select.setText(_translate("Dialog", "选择主体图"))
        self.groupBox.setTitle(_translate("Dialog", "背景图"))
        self.groupBox_2.setTitle(_translate("Dialog", "主体图"))
