# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZipDirUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(546, 198)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        Form.setFont(font)
        Form.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 2)
        self.lineEdit_pwd = QtWidgets.QLineEdit(Form)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.gridLayout.addWidget(self.lineEdit_pwd, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_dir = QtWidgets.QLineEdit(Form)
        self.lineEdit_dir.setReadOnly(True)
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.gridLayout.addWidget(self.lineEdit_dir, 0, 1, 1, 1)
        self.pushButton_select_dir = QtWidgets.QPushButton(Form)
        self.pushButton_select_dir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_select_dir.setObjectName("pushButton_select_dir")
        self.gridLayout.addWidget(self.pushButton_select_dir, 0, 2, 1, 1)
        self.pushButton_select_zip = QtWidgets.QPushButton(Form)
        self.pushButton_select_zip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_select_zip.setObjectName("pushButton_select_zip")
        self.gridLayout.addWidget(self.pushButton_select_zip, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_compression = QtWidgets.QPushButton(Form)
        self.pushButton_compression.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_compression.setObjectName("pushButton_compression")
        self.horizontalLayout_2.addWidget(self.pushButton_compression)
        self.pushButton_decompression = QtWidgets.QPushButton(Form)
        self.pushButton_decompression.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_decompression.setObjectName("pushButton_decompression")
        self.horizontalLayout_2.addWidget(self.pushButton_decompression)
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout_2.addWidget(self.pushButton_exit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label_3.setText(_translate("Form", "文件夹加密压缩/解压缩"))
        self.label.setText(_translate("Form", "压缩文件夹/解压zip文件："))
        self.checkBox.setText(_translate("Form", "是否删除原文件夹/文件"))
        self.label_2.setText(_translate("Form", "加/解密密码："))
        self.pushButton_select_dir.setText(_translate("Form", "选择文件夹"))
        self.pushButton_select_zip.setText(_translate("Form", "选择文件"))
        self.pushButton_compression.setText(_translate("Form", "压缩&&加密"))
        self.pushButton_decompression.setText(_translate("Form", "解压&&解密"))
        self.pushButton_exit.setText(_translate("Form", "退出"))
